name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy types-PyYAML pandas-stubs

      - name: Run flake8
        run: |
          flake8 . --max-line-length=88

      - name: Run mypy
        run: |
          python -m mypy main.py

  test:
    name: Run tests & Collect Coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=. --maxfail=1 --disable-warnings -q

      - name: Generate coverage XML
        run: |
          python -m pytest --cov=. --cov-report xml:coverage.xml -q

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
