name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy types-PyYAML pandas-stubs

      - run: flake8 . --max-line-length=88
      - run: python -m mypy main.py

  test:
    name: Run tests & Collect Coverage
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-cov

      - run: python -m pytest --cov=. --maxfail=1 --disable-warnings -q
      - run: python -m pytest --cov=. --cov-report xml:coverage.xml -q
      # <<--- шаг Upload coverage report удалён
